language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1

before_install:
  - gem install bundler
  - bundle --version

env:
  # None for now
gemfile:
  - Gemfile
services:
  # None for now
notifications:
  # None for now
sudo: false
